// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_log.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/zeitwork/zeitwork/internal/shared/uuid"
)

const deploymentLogCreate = `-- name: DeploymentLogCreate :exec
INSERT INTO deployment_logs (id, deployment_id, message, level, organisation_id, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
`

type DeploymentLogCreateParams struct {
	ID             uuid.UUID   `json:"id"`
	DeploymentID   uuid.UUID   `json:"deployment_id"`
	Message        string      `json:"message"`
	Level          pgtype.Text `json:"level"`
	OrganisationID uuid.UUID   `json:"organisation_id"`
}

func (q *Queries) DeploymentLogCreate(ctx context.Context, arg DeploymentLogCreateParams) error {
	_, err := q.db.Exec(ctx, deploymentLogCreate,
		arg.ID,
		arg.DeploymentID,
		arg.Message,
		arg.Level,
		arg.OrganisationID,
	)
	return err
}
