// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain.sql

package queries

import (
	"context"

	"github.com/zeitwork/zeitwork/internal/shared/uuid"
)

const domainFind = `-- name: DomainFind :many
SELECT id, name, project_id, deployment_id, verified_at, organisation_id, created_at, updated_at, deleted_at, txt_verification_required, redirect_to, redirect_status_code
FROM domains
`

func (q *Queries) DomainFind(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, domainFind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.DeploymentID,
			&i.VerifiedAt,
			&i.OrganisationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TxtVerificationRequired,
			&i.RedirectTo,
			&i.RedirectStatusCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainFindActiveByName = `-- name: DomainFindActiveByName :many
SELECT id, name, project_id, deployment_id, verified_at, organisation_id, created_at, updated_at, deleted_at, txt_verification_required, redirect_to, redirect_status_code
FROM domains
WHERE name = $1 AND id != $2 AND deleted_at IS NULL
`

type DomainFindActiveByNameParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

// Find all active (non-deleted) domains with a given name, excluding a specific domain ID
func (q *Queries) DomainFindActiveByName(ctx context.Context, arg DomainFindActiveByNameParams) ([]Domain, error) {
	rows, err := q.db.Query(ctx, domainFindActiveByName, arg.Name, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.DeploymentID,
			&i.VerifiedAt,
			&i.OrganisationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TxtVerificationRequired,
			&i.RedirectTo,
			&i.RedirectStatusCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainFirstByID = `-- name: DomainFirstByID :one
SELECT id, name, project_id, deployment_id, verified_at, organisation_id, created_at, updated_at, deleted_at, txt_verification_required, redirect_to, redirect_status_code
FROM domains
WHERE id = $1
LIMIT 1
`

func (q *Queries) DomainFirstByID(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, domainFirstByID, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.DeploymentID,
		&i.VerifiedAt,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TxtVerificationRequired,
		&i.RedirectTo,
		&i.RedirectStatusCode,
	)
	return i, err
}

const domainUpdateDeploymentForProject = `-- name: DomainUpdateDeploymentForProject :exec
UPDATE domains
SET deployment_id = $1, updated_at = now()
WHERE project_id = $2
  AND name NOT LIKE '%.zeitwork.app'
  AND deleted_at IS NULL
`

type DomainUpdateDeploymentForProjectParams struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	ProjectID    uuid.UUID `json:"project_id"`
}

// Update all custom domains (non-zeitwork.app) for a project to point to a new deployment
func (q *Queries) DomainUpdateDeploymentForProject(ctx context.Context, arg DomainUpdateDeploymentForProjectParams) error {
	_, err := q.db.Exec(ctx, domainUpdateDeploymentForProject, arg.DeploymentID, arg.ProjectID)
	return err
}
