// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const domainFind = `-- name: DomainFind :many
SELECT id, name, project_id, deployment_id, verified_at, organisation_id, created_at, updated_at, deleted_at
FROM domains
`

func (q *Queries) DomainFind(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, domainFind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.DeploymentID,
			&i.VerifiedAt,
			&i.OrganisationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainFirstByID = `-- name: DomainFirstByID :one
SELECT id, name, project_id, deployment_id, verified_at, organisation_id, created_at, updated_at, deleted_at
FROM domains
WHERE id = $1
LIMIT 1
`

func (q *Queries) DomainFirstByID(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, domainFirstByID, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.DeploymentID,
		&i.VerifiedAt,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
