// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edgeproxy.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/zeitwork/zeitwork/internal/shared/uuid"
)

const domainVerified = `-- name: DomainVerified :one
SELECT verified_at
FROM domains
WHERE name = $1 AND deleted_at IS NULL
`

// Checks if a domain exists and is verified (for on-demand certificate issuance)
func (q *Queries) DomainVerified(ctx context.Context, name string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, domainVerified, name)
	var verified_at pgtype.Timestamptz
	err := row.Scan(&verified_at)
	return verified_at, err
}

const routeFindActive = `-- name: RouteFindActive :many
SELECT d.name       AS domain_name,
       v.port       AS vm_port,
       v.id         AS vm_id,
       v.ip_address AS vm_ip,
       v.server_id  AS server_id
FROM domains d
         INNER JOIN deployments dep ON d.deployment_id = dep.id
         INNER JOIN vms v ON dep.vm_id = v.id
WHERE d.verified_at IS NOT NULL
  AND d.deleted_at IS NULL
  AND (dep.stopped_at IS NULL AND dep.failed_at IS NULL AND dep.deleted_at IS NULL)
  AND v.deleted_at IS NULL
ORDER BY d.name
`

type RouteFindActiveRow struct {
	DomainName string       `json:"domain_name"`
	VmPort     pgtype.Int4  `json:"vm_port"`
	VmID       uuid.UUID    `json:"vm_id"`
	VmIp       netip.Prefix `json:"vm_ip"`
	ServerID   uuid.UUID    `json:"server_id"`
}

// Domains -> Deployment -> VM -> Server
// Returns routes with server info so the edge proxy knows which server hosts each VM.
// With L2 routing between servers, the edge proxy can reach any VM directly by IP.
func (q *Queries) RouteFindActive(ctx context.Context) ([]RouteFindActiveRow, error) {
	rows, err := q.db.Query(ctx, routeFindActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RouteFindActiveRow{}
	for rows.Next() {
		var i RouteFindActiveRow
		if err := rows.Scan(
			&i.DomainName,
			&i.VmPort,
			&i.VmID,
			&i.VmIp,
			&i.ServerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
