// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edgeproxy.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/zeitwork/zeitwork/internal/shared/uuid"
)

const domainVerified = `-- name: DomainVerified :one
SELECT verified_at
FROM domains
WHERE name = $1
`

// Checks if a domain exists and is verified (for on-demand certificate issuance)
func (q *Queries) DomainVerified(ctx context.Context, name string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, domainVerified, name)
	var verified_at pgtype.Timestamptz
	err := row.Scan(&verified_at)
	return verified_at, err
}

const routeFindActive = `-- name: RouteFindActive :many
SELECT
    d.name as domain_name,
    v.port as vm_port,
    v.id as vm_id,
    v.ip_address as vm_ip,
    v.server_id as server_id,
    s.internal_ip as server_internal_ip
FROM domains d
         INNER JOIN deployments dep ON d.deployment_id = dep.id
         INNER JOIN vms v ON dep.vm_id = v.id
         LEFT JOIN servers s ON v.server_id = s.id
WHERE d.verified_at IS NOT NULL
  AND dep.status = 'running'
  AND v.status = 'running'
ORDER BY d.name
`

type RouteFindActiveRow struct {
	DomainName       string       `json:"domain_name"`
	VmPort           pgtype.Int4  `json:"vm_port"`
	VmID             uuid.UUID    `json:"vm_id"`
	VmIp             netip.Prefix `json:"vm_ip"`
	ServerID         uuid.UUID    `json:"server_id"`
	ServerInternalIp pgtype.Text  `json:"server_internal_ip"`
}

// Domains -> Deployment -> VM -> Server
// Returns routes with server info so the edge proxy can forward cross-server.
func (q *Queries) RouteFindActive(ctx context.Context) ([]RouteFindActiveRow, error) {
	rows, err := q.db.Query(ctx, routeFindActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RouteFindActiveRow{}
	for rows.Next() {
		var i RouteFindActiveRow
		if err := rows.Scan(
			&i.DomainName,
			&i.VmPort,
			&i.VmID,
			&i.VmIp,
			&i.ServerID,
			&i.ServerInternalIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
