// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environment_variable.sql

package queries

import (
	"context"

	"github.com/zeitwork/zeitwork/internal/shared/uuid"
)

const environmentVariableFindByProjectID = `-- name: EnvironmentVariableFindByProjectID :many
SELECT name, value FROM environment_variables 
WHERE project_id = $1 AND deleted_at IS NULL
`

type EnvironmentVariableFindByProjectIDRow struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

func (q *Queries) EnvironmentVariableFindByProjectID(ctx context.Context, projectID uuid.UUID) ([]EnvironmentVariableFindByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, environmentVariableFindByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentVariableFindByProjectIDRow{}
	for rows.Next() {
		var i EnvironmentVariableFindByProjectIDRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
