// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const githubInstallationFindByID = `-- name: GithubInstallationFindByID :one
SELECT id, user_id, github_account_id, github_installation_id, organisation_id, created_at, updated_at, deleted_at
FROM github_installations
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GithubInstallationFindByID(ctx context.Context, id uuid.UUID) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, githubInstallationFindByID, id)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubAccountID,
		&i.GithubInstallationID,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
