// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/zeitwork/zeitwork/internal/shared/uuid"
)

const imageCreate = `-- name: ImageCreate :one
insert into images (id, registry, repository, tag)
VALUES ($1, $2, $3, $4)
RETURNING id, registry, repository, tag, created_at, updated_at, deleted_at
`

type ImageCreateParams struct {
	ID         uuid.UUID `json:"id"`
	Registry   string    `json:"registry"`
	Repository string    `json:"repository"`
	Tag        string    `json:"tag"`
}

func (q *Queries) ImageCreate(ctx context.Context, arg ImageCreateParams) (Image, error) {
	row := q.db.QueryRow(ctx, imageCreate,
		arg.ID,
		arg.Registry,
		arg.Repository,
		arg.Tag,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Registry,
		&i.Repository,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const imageFind = `-- name: ImageFind :many
select id, registry, repository, tag, created_at, updated_at, deleted_at from images
`

func (q *Queries) ImageFind(ctx context.Context) ([]Image, error) {
	rows, err := q.db.Query(ctx, imageFind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Registry,
			&i.Repository,
			&i.Tag,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const imageFindByID = `-- name: ImageFindByID :one
select id, registry, repository, tag, created_at, updated_at, deleted_at from images where id=$1
`

func (q *Queries) ImageFindByID(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, imageFindByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Registry,
		&i.Repository,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const imageFindByRepositoryAndTag = `-- name: ImageFindByRepositoryAndTag :one
select id, registry, repository, tag, created_at, updated_at, deleted_at
from images
where registry = $1
  and repository = $2
  and tag = $3
limit 1
`

type ImageFindByRepositoryAndTagParams struct {
	Registry   string `json:"registry"`
	Repository string `json:"repository"`
	Tag        string `json:"tag"`
}

func (q *Queries) ImageFindByRepositoryAndTag(ctx context.Context, arg ImageFindByRepositoryAndTagParams) (Image, error) {
	row := q.db.QueryRow(ctx, imageFindByRepositoryAndTag, arg.Registry, arg.Repository, arg.Tag)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Registry,
		&i.Repository,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const imageFindOrCreate = `-- name: ImageFindOrCreate :one
WITH ins AS (
    INSERT INTO images (id, registry, repository, tag)
    VALUES ($1, $2, $3, $4)
    ON CONFLICT (registry, repository, tag) DO NOTHING
    RETURNING id, registry, repository, tag, created_at, updated_at, deleted_at
)
SELECT id, registry, repository, tag, created_at, updated_at, deleted_at FROM ins
UNION ALL
SELECT id, registry, repository, tag, created_at, updated_at, deleted_at FROM images
WHERE registry = $2 AND repository = $3 AND tag = $4
  AND NOT EXISTS (SELECT 1 FROM ins)
LIMIT 1
`

type ImageFindOrCreateParams struct {
	ID         uuid.UUID `json:"id"`
	Registry   string    `json:"registry"`
	Repository string    `json:"repository"`
	Tag        string    `json:"tag"`
}

type ImageFindOrCreateRow struct {
	ID         uuid.UUID          `json:"id"`
	Registry   string             `json:"registry"`
	Repository string             `json:"repository"`
	Tag        string             `json:"tag"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ImageFindOrCreate(ctx context.Context, arg ImageFindOrCreateParams) (ImageFindOrCreateRow, error) {
	row := q.db.QueryRow(ctx, imageFindOrCreate,
		arg.ID,
		arg.Registry,
		arg.Repository,
		arg.Tag,
	)
	var i ImageFindOrCreateRow
	err := row.Scan(
		&i.ID,
		&i.Registry,
		&i.Repository,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
