// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/zeitwork/zeitwork/internal/shared/uuid"
)

type BuildStatus string

const (
	BuildStatusPending   BuildStatus = "pending"
	BuildStatusBuilding  BuildStatus = "building"
	BuildStatusSuccesful BuildStatus = "succesful"
	BuildStatusFailed    BuildStatus = "failed"
)

func (e *BuildStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildStatus(s)
	case string:
		*e = BuildStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildStatus: %T", src)
	}
	return nil
}

type NullBuildStatus struct {
	BuildStatus BuildStatus `json:"build_status"`
	Valid       bool        `json:"valid"` // Valid is true if BuildStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BuildStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildStatus), nil
}

type DeploymentStatus string

const (
	DeploymentStatusPending  DeploymentStatus = "pending"
	DeploymentStatusBuilding DeploymentStatus = "building"
	DeploymentStatusStarting DeploymentStatus = "starting"
	DeploymentStatusRunning  DeploymentStatus = "running"
	DeploymentStatusStopping DeploymentStatus = "stopping"
	DeploymentStatusStopped  DeploymentStatus = "stopped"
	DeploymentStatusFailed   DeploymentStatus = "failed"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus `json:"deployment_status"`
	Valid            bool             `json:"valid"` // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type VmStatus string

const (
	VmStatusPending  VmStatus = "pending"
	VmStatusStarting VmStatus = "starting"
	VmStatusRunning  VmStatus = "running"
	VmStatusStopping VmStatus = "stopping"
	VmStatusStopped  VmStatus = "stopped"
	VmStatusFailed   VmStatus = "failed"
)

func (e *VmStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VmStatus(s)
	case string:
		*e = VmStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VmStatus: %T", src)
	}
	return nil
}

type NullVmStatus struct {
	VmStatus VmStatus `json:"vm_status"`
	Valid    bool     `json:"valid"` // Valid is true if VmStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVmStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VmStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VmStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVmStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VmStatus), nil
}

type Build struct {
	ID             uuid.UUID          `json:"id"`
	Status         BuildStatus        `json:"status"`
	ProjectID      uuid.UUID          `json:"project_id"`
	GithubCommit   string             `json:"github_commit"`
	GithubBranch   string             `json:"github_branch"`
	ImageID        uuid.UUID          `json:"image_id"`
	VmID           uuid.UUID          `json:"vm_id"`
	PendingAt      pgtype.Timestamptz `json:"pending_at"`
	BuildingAt     pgtype.Timestamptz `json:"building_at"`
	SuccessfulAt   pgtype.Timestamptz `json:"successful_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type BuildLog struct {
	ID             uuid.UUID          `json:"id"`
	BuildID        uuid.UUID          `json:"build_id"`
	Message        string             `json:"message"`
	Level          string             `json:"level"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CertmagicDatum struct {
	Key      string             `json:"key"`
	Value    string             `json:"value"`
	Modified pgtype.Timestamptz `json:"modified"`
}

type CertmagicLock struct {
	Key     string             `json:"key"`
	Expires pgtype.Timestamptz `json:"expires"`
}

type Deployment struct {
	ID             uuid.UUID          `json:"id"`
	Status         DeploymentStatus   `json:"status"`
	GithubCommit   string             `json:"github_commit"`
	ProjectID      uuid.UUID          `json:"project_id"`
	BuildID        uuid.UUID          `json:"build_id"`
	ImageID        uuid.UUID          `json:"image_id"`
	VmID           uuid.UUID          `json:"vm_id"`
	PendingAt      pgtype.Timestamptz `json:"pending_at"`
	BuildingAt     pgtype.Timestamptz `json:"building_at"`
	StartingAt     pgtype.Timestamptz `json:"starting_at"`
	RunningAt      pgtype.Timestamptz `json:"running_at"`
	StoppingAt     pgtype.Timestamptz `json:"stopping_at"`
	StoppedAt      pgtype.Timestamptz `json:"stopped_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type DeploymentLog struct {
	ID             uuid.UUID          `json:"id"`
	DeploymentID   uuid.UUID          `json:"deployment_id"`
	Message        string             `json:"message"`
	Level          pgtype.Text        `json:"level"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Domain struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	ProjectID      uuid.UUID          `json:"project_id"`
	DeploymentID   uuid.UUID          `json:"deployment_id"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type EnvironmentVariable struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Value          string             `json:"value"`
	ProjectID      uuid.UUID          `json:"project_id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type GithubInstallation struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	GithubAccountID      int32              `json:"github_account_id"`
	GithubInstallationID int32              `json:"github_installation_id"`
	OrganisationID       uuid.UUID          `json:"organisation_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type Image struct {
	ID           uuid.UUID          `json:"id"`
	Registry     string             `json:"registry"`
	Repository   string             `json:"repository"`
	Tag          string             `json:"tag"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DiskImageKey pgtype.Text        `json:"disk_image_key"`
}

type Organisation struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type OrganisationMember struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	OrganisationID uuid.UUID          `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Project struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	GithubRepository     string             `json:"github_repository"`
	GithubInstallationID uuid.UUID          `json:"github_installation_id"`
	OrganisationID       uuid.UUID          `json:"organisation_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Email             string             `json:"email"`
	Username          string             `json:"username"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	GithubAccountID   pgtype.Int4        `json:"github_account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Vm struct {
	ID           uuid.UUID          `json:"id"`
	Vcpus        int32              `json:"vcpus"`
	Memory       int32              `json:"memory"`
	Status       VmStatus           `json:"status"`
	ImageID      uuid.UUID          `json:"image_id"`
	Port         pgtype.Int4        `json:"port"`
	IpAddress    netip.Prefix       `json:"ip_address"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	PendingAt    pgtype.Timestamptz `json:"pending_at"`
	StartingAt   pgtype.Timestamptz `json:"starting_at"`
	RunningAt    pgtype.Timestamptz `json:"running_at"`
	StoppingAt   pgtype.Timestamptz `json:"stopping_at"`
	StoppedAt    pgtype.Timestamptz `json:"stopped_at"`
	FailedAt     pgtype.Timestamptz `json:"failed_at"`
	EnvVariables pgtype.Text        `json:"env_variables"`
}
