// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BuildStatus string

const (
	BuildStatusPending   BuildStatus = "pending"
	BuildStatusBuilding  BuildStatus = "building"
	BuildStatusSuccesful BuildStatus = "succesful"
	BuildStatusFailed    BuildStatus = "failed"
)

func (e *BuildStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildStatus(s)
	case string:
		*e = BuildStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildStatus: %T", src)
	}
	return nil
}

type NullBuildStatus struct {
	BuildStatus BuildStatus `json:"build_status"`
	Valid       bool        `json:"valid"` // Valid is true if BuildStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BuildStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildStatus), nil
}

type DeploymentStatus string

const (
	DeploymentStatusPending  DeploymentStatus = "pending"
	DeploymentStatusBuilding DeploymentStatus = "building"
	DeploymentStatusStarting DeploymentStatus = "starting"
	DeploymentStatusRunning  DeploymentStatus = "running"
	DeploymentStatusStopping DeploymentStatus = "stopping"
	DeploymentStatusStopped  DeploymentStatus = "stopped"
	DeploymentStatusFailed   DeploymentStatus = "failed"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus `json:"deployment_status"`
	Valid            bool             `json:"valid"` // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type VmStatus string

const (
	VmStatusPending  VmStatus = "pending"
	VmStatusStarting VmStatus = "starting"
	VmStatusRunning  VmStatus = "running"
	VmStatusStopping VmStatus = "stopping"
	VmStatusStopped  VmStatus = "stopped"
	VmStatusFailed   VmStatus = "failed"
)

func (e *VmStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VmStatus(s)
	case string:
		*e = VmStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VmStatus: %T", src)
	}
	return nil
}

type NullVmStatus struct {
	VmStatus VmStatus `json:"vm_status"`
	Valid    bool     `json:"valid"` // Valid is true if VmStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVmStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VmStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VmStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVmStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VmStatus), nil
}

type Build struct {
	ID             pgtype.UUID        `json:"id"`
	Status         BuildStatus        `json:"status"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	GithubCommit   string             `json:"github_commit"`
	GithubBranch   string             `json:"github_branch"`
	ImageID        pgtype.UUID        `json:"image_id"`
	VmID           pgtype.UUID        `json:"vm_id"`
	PendingAt      pgtype.Timestamptz `json:"pending_at"`
	BuildingAt     pgtype.Timestamptz `json:"building_at"`
	SuccessfulAt   pgtype.Timestamptz `json:"successful_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type BuildLog struct {
	ID             pgtype.UUID        `json:"id"`
	BuildID        pgtype.UUID        `json:"build_id"`
	Message        string             `json:"message"`
	Level          string             `json:"level"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CertmagicDatum struct {
	Key      string             `json:"key"`
	Value    string             `json:"value"`
	Modified pgtype.Timestamptz `json:"modified"`
}

type CertmagicLock struct {
	Key     string             `json:"key"`
	Expires pgtype.Timestamptz `json:"expires"`
}

type Deployment struct {
	ID             pgtype.UUID        `json:"id"`
	Status         DeploymentStatus   `json:"status"`
	GithubCommit   string             `json:"github_commit"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	BuildID        pgtype.UUID        `json:"build_id"`
	ImageID        pgtype.UUID        `json:"image_id"`
	VmID           pgtype.UUID        `json:"vm_id"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type DeploymentLog struct {
	ID             pgtype.UUID        `json:"id"`
	DeploymentID   pgtype.UUID        `json:"deployment_id"`
	Message        string             `json:"message"`
	Level          pgtype.Text        `json:"level"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Domain struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	DeploymentID   pgtype.UUID        `json:"deployment_id"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type EnvironmentVariable struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Value          string             `json:"value"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type GithubInstallation struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	GithubAccountID      int32              `json:"github_account_id"`
	GithubInstallationID int32              `json:"github_installation_id"`
	OrganisationID       pgtype.UUID        `json:"organisation_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type Image struct {
	ID         pgtype.UUID        `json:"id"`
	Registry   string             `json:"registry"`
	Repository string             `json:"repository"`
	Tag        string             `json:"tag"`
	Digest     string             `json:"digest"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Organisation struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type OrganisationMember struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Project struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	GithubRepository     string             `json:"github_repository"`
	GithubInstallationID pgtype.UUID        `json:"github_installation_id"`
	OrganisationID       pgtype.UUID        `json:"organisation_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Email             string             `json:"email"`
	Username          string             `json:"username"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	GithubAccountID   pgtype.Int4        `json:"github_account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Vm struct {
	ID        pgtype.UUID        `json:"id"`
	Vcpus     int32              `json:"vcpus"`
	Memory    int32              `json:"memory"`
	Status    VmStatus           `json:"status"`
	ImageID   pgtype.UUID        `json:"image_id"`
	Port      pgtype.Int4        `json:"port"`
	IpAddress pgtype.Text        `json:"ip_address"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
