// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package queries

import (
	"context"

	"github.com/zeitwork/zeitwork/internal/shared/uuid"
)

const projectFirstByID = `-- name: ProjectFirstByID :one
SELECT id, name, slug, github_repository, github_installation_id, organisation_id, created_at, updated_at, deleted_at, root_directory
FROM projects
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) ProjectFirstByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, projectFirstByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.GithubRepository,
		&i.GithubInstallationID,
		&i.OrganisationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RootDirectory,
	)
	return i, err
}
