// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vm.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/zeitwork/zeitwork/internal/shared/uuid"
)

const vMCreate = `-- name: VMCreate :one
INSERT INTO vms (id, vcpus, memory, status, image_id, port, ip_address, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, vcpus, memory, status, image_id, port, ip_address, metadata, created_at, updated_at, deleted_at, pending_at, starting_at, running_at, stopping_at, stopped_at, failed_at
`

type VMCreateParams struct {
	ID        uuid.UUID    `json:"id"`
	Vcpus     int32        `json:"vcpus"`
	Memory    int32        `json:"memory"`
	Status    VmStatus     `json:"status"`
	ImageID   uuid.UUID    `json:"image_id"`
	Port      pgtype.Int4  `json:"port"`
	IpAddress netip.Prefix `json:"ip_address"`
	Metadata  []byte       `json:"metadata"`
}

func (q *Queries) VMCreate(ctx context.Context, arg VMCreateParams) (Vm, error) {
	row := q.db.QueryRow(ctx, vMCreate,
		arg.ID,
		arg.Vcpus,
		arg.Memory,
		arg.Status,
		arg.ImageID,
		arg.Port,
		arg.IpAddress,
		arg.Metadata,
	)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Vcpus,
		&i.Memory,
		&i.Status,
		&i.ImageID,
		&i.Port,
		&i.IpAddress,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PendingAt,
		&i.StartingAt,
		&i.RunningAt,
		&i.StoppingAt,
		&i.StoppedAt,
		&i.FailedAt,
	)
	return i, err
}

const vMFind = `-- name: VMFind :many
SELECT id, vcpus, memory, status, image_id, port, ip_address, metadata, created_at, updated_at, deleted_at, pending_at, starting_at, running_at, stopping_at, stopped_at, failed_at
FROM vms
`

func (q *Queries) VMFind(ctx context.Context) ([]Vm, error) {
	rows, err := q.db.Query(ctx, vMFind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Vcpus,
			&i.Memory,
			&i.Status,
			&i.ImageID,
			&i.Port,
			&i.IpAddress,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PendingAt,
			&i.StartingAt,
			&i.RunningAt,
			&i.StoppingAt,
			&i.StoppedAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vMFindByImageID = `-- name: VMFindByImageID :many
SELECT id, vcpus, memory, status, image_id, port, ip_address, metadata, created_at, updated_at, deleted_at, pending_at, starting_at, running_at, stopping_at, stopped_at, failed_at FROM vms WHERE image_id = $1
`

func (q *Queries) VMFindByImageID(ctx context.Context, imageID uuid.UUID) ([]Vm, error) {
	rows, err := q.db.Query(ctx, vMFindByImageID, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Vcpus,
			&i.Memory,
			&i.Status,
			&i.ImageID,
			&i.Port,
			&i.IpAddress,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PendingAt,
			&i.StartingAt,
			&i.RunningAt,
			&i.StoppingAt,
			&i.StoppedAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vMFirstByID = `-- name: VMFirstByID :one
SELECT id, vcpus, memory, status, image_id, port, ip_address, metadata, created_at, updated_at, deleted_at, pending_at, starting_at, running_at, stopping_at, stopped_at, failed_at
FROM vms
WHERE id = $1
LIMIT 1
`

func (q *Queries) VMFirstByID(ctx context.Context, id uuid.UUID) (Vm, error) {
	row := q.db.QueryRow(ctx, vMFirstByID, id)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Vcpus,
		&i.Memory,
		&i.Status,
		&i.ImageID,
		&i.Port,
		&i.IpAddress,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PendingAt,
		&i.StartingAt,
		&i.RunningAt,
		&i.StoppingAt,
		&i.StoppedAt,
		&i.FailedAt,
	)
	return i, err
}

const vMNextIPAddress = `-- name: VMNextIPAddress :one
WITH lock AS (
    SELECT pg_advisory_xact_lock(hashtext('vm_ip_allocation'))
)
SELECT COALESCE(
               (SELECT set_masklen((ip_address + 2)::inet, 31)
                FROM vms
                WHERE deleted_at IS NULL
                ORDER BY ip_address DESC
                LIMIT 1),
               '10.0.0.1/31'::inet  -- First VM gets 10.0.0.1, host side is 10.0.0.0
       ) AS next_ip
FROM lock
`

// Each VM needs its own /31 subnet, so we increment by 2 to skip to the next block
// Block 1: 10.0.0.0/31 -> host=10.0.0.0, vm=10.0.0.1
// Block 2: 10.0.0.2/31 -> host=10.0.0.2, vm=10.0.0.3
// etc.
func (q *Queries) VMNextIPAddress(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, vMNextIPAddress)
	var next_ip interface{}
	err := row.Scan(&next_ip)
	return next_ip, err
}

const vMSoftDelete = `-- name: VMSoftDelete :exec
UPDATE vms
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) VMSoftDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, vMSoftDelete, id)
	return err
}

const vMUpdateStatus = `-- name: VMUpdateStatus :one
update vms set status = $1 where id=$2 returning id, vcpus, memory, status, image_id, port, ip_address, metadata, created_at, updated_at, deleted_at, pending_at, starting_at, running_at, stopping_at, stopped_at, failed_at
`

type VMUpdateStatusParams struct {
	Status VmStatus  `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) VMUpdateStatus(ctx context.Context, arg VMUpdateStatusParams) (Vm, error) {
	row := q.db.QueryRow(ctx, vMUpdateStatus, arg.Status, arg.ID)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Vcpus,
		&i.Memory,
		&i.Status,
		&i.ImageID,
		&i.Port,
		&i.IpAddress,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PendingAt,
		&i.StartingAt,
		&i.RunningAt,
		&i.StoppingAt,
		&i.StoppedAt,
		&i.FailedAt,
	)
	return i, err
}
