// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vm.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const vMFind = `-- name: VMFind :many
SELECT id, vcpus, memory, status, image_id, port, ip_address, metadata, created_at, updated_at, deleted_at
FROM vms
`

func (q *Queries) VMFind(ctx context.Context) ([]Vm, error) {
	rows, err := q.db.Query(ctx, vMFind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vm{}
	for rows.Next() {
		var i Vm
		if err := rows.Scan(
			&i.ID,
			&i.Vcpus,
			&i.Memory,
			&i.Status,
			&i.ImageID,
			&i.Port,
			&i.IpAddress,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vMFirstByID = `-- name: VMFirstByID :one
SELECT id, vcpus, memory, status, image_id, port, ip_address, metadata, created_at, updated_at, deleted_at
FROM vms
WHERE id = $1
LIMIT 1
`

func (q *Queries) VMFirstByID(ctx context.Context, id uuid.UUID) (Vm, error) {
	row := q.db.QueryRow(ctx, vMFirstByID, id)
	var i Vm
	err := row.Scan(
		&i.ID,
		&i.Vcpus,
		&i.Memory,
		&i.Status,
		&i.ImageID,
		&i.Port,
		&i.IpAddress,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
