// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: zeitwork.sql

package queries

import (
	"context"

	"github.com/zeitwork/zeitwork/internal/shared/uuid"
)

const domainListUnverified = `-- name: DomainListUnverified :many
SELECT id, name, project_id, deployment_id, verified_at, organisation_id, created_at, updated_at, deleted_at, txt_verification_required
FROM domains
WHERE verified_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) DomainListUnverified(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, domainListUnverified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.DeploymentID,
			&i.VerifiedAt,
			&i.OrganisationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TxtVerificationRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainMarkVerified = `-- name: DomainMarkVerified :exec
UPDATE domains
SET verified_at = NOW()
WHERE id = $1
`

func (q *Queries) DomainMarkVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, domainMarkVerified, id)
	return err
}

const domainSoftDelete = `-- name: DomainSoftDelete :exec
UPDATE domains
SET deleted_at = NOW(), verified_at = NULL
WHERE id = $1
`

func (q *Queries) DomainSoftDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, domainSoftDelete, id)
	return err
}
