// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Deployment struct {
	ID             pgtype.UUID        `json:"id"`
	DeploymentID   string             `json:"deployment_id"`
	Status         string             `json:"status"`
	CommitHash     string             `json:"commit_hash"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	EnvironmentID  pgtype.UUID        `json:"environment_id"`
	ImageID        pgtype.UUID        `json:"image_id"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type DeploymentInstance struct {
	ID             pgtype.UUID        `json:"id"`
	DeploymentID   pgtype.UUID        `json:"deployment_id"`
	InstanceID     pgtype.UUID        `json:"instance_id"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Domain struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	VerificationToken pgtype.Text        `json:"verification_token"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	DeploymentID      pgtype.UUID        `json:"deployment_id"`
	Internal          bool               `json:"internal"`
	OrganisationID    pgtype.UUID        `json:"organisation_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type GithubInstallation struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	GithubAccountID      int32              `json:"github_account_id"`
	GithubInstallationID int32              `json:"github_installation_id"`
	OrganisationID       pgtype.UUID        `json:"organisation_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type Image struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	ImageSize pgtype.Int4        `json:"image_size"`
	ImageHash string             `json:"image_hash"`
	ObjectKey pgtype.Text        `json:"object_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ImageBuild struct {
	ID             pgtype.UUID        `json:"id"`
	Status         string             `json:"status"`
	DeploymentID   pgtype.UUID        `json:"deployment_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Instance struct {
	ID                   pgtype.UUID        `json:"id"`
	RegionID             pgtype.UUID        `json:"region_id"`
	NodeID               pgtype.UUID        `json:"node_id"`
	ImageID              pgtype.UUID        `json:"image_id"`
	State                string             `json:"state"`
	Vcpus                int32              `json:"vcpus"`
	Memory               int32              `json:"memory"`
	DefaultPort          int32              `json:"default_port"`
	Ipv6Address          string             `json:"ipv6_address"`
	EnvironmentVariables string             `json:"environment_variables"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type Node struct {
	ID        pgtype.UUID        `json:"id"`
	RegionID  pgtype.UUID        `json:"region_id"`
	Hostname  string             `json:"hostname"`
	IpAddress string             `json:"ip_address"`
	State     string             `json:"state"`
	Resources json.RawMessage    `json:"resources"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Organisation struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type OrganisationMember struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Project struct {
	ID                   pgtype.UUID        `json:"id"`
	Name                 string             `json:"name"`
	Slug                 string             `json:"slug"`
	GithubRepository     string             `json:"github_repository"`
	DefaultBranch        string             `json:"default_branch"`
	LatestDeploymentID   pgtype.UUID        `json:"latest_deployment_id"`
	OrganisationID       pgtype.UUID        `json:"organisation_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	GithubInstallationID int32              `json:"github_installation_id"`
}

type ProjectEnvironment struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type ProjectSecret struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Value          string             `json:"value"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	EnvironmentID  pgtype.UUID        `json:"environment_id"`
	OrganisationID pgtype.UUID        `json:"organisation_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Region struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	Country   string             `json:"country"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type SslCert struct {
	ID        pgtype.UUID        `json:"id"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type SslLock struct {
	ID        pgtype.UUID        `json:"id"`
	Key       string             `json:"key"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	Username        string             `json:"username"`
	GithubAccountID pgtype.Int4        `json:"github_account_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Waitlist struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
