// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Attempts to acquire a lock for a key
	AcquireCertmagicLock(ctx context.Context, arg *AcquireCertmagicLockParams) (int64, error)
	// Assign a VM to a deployment and update VM status
	AssignVMToDeployment(ctx context.Context, arg *AssignVMToDeploymentParams) error
	// Removes expired locks
	CleanupExpiredCertmagicLocks(ctx context.Context) error
	// Clear VM assignment from deployment
	ClearDeploymentVM(ctx context.Context, id pgtype.UUID) error
	// Clear image from VM
	ClearVMImage(ctx context.Context, id pgtype.UUID) error
	// Create a new build for a deployment
	CreateBuild(ctx context.Context, arg *CreateBuildParams) (*Build, error)
	// Create new image record
	CreateImage(ctx context.Context, arg *CreateImageParams) error
	// Create a new region
	CreateRegion(ctx context.Context, arg *CreateRegionParams) (*Region, error)
	// Create a new VM
	CreateVM(ctx context.Context, arg *CreateVMParams) (*Vm, error)
	// Deletes a certmagic data entry by key
	DeleteCertmagicData(ctx context.Context, key string) (int64, error)
	// Checks if a certmagic data entry exists
	ExistsCertmagicData(ctx context.Context, key string) (bool, error)
	// Returns active routing information for the edgeproxy
	// Joins domains → deployments → vms → regions
	GetActiveRoutes(ctx context.Context) ([]*GetActiveRoutesRow, error)
	// Get all regions
	GetAllRegions(ctx context.Context) ([]*Region, error)
	// Get building deployments that have a build but no image yet
	GetBuildingDeploymentsWithoutImage(ctx context.Context) ([]*GetBuildingDeploymentsWithoutImageRow, error)
	// Get building deployments that have an image but no VM assigned
	GetBuildingDeploymentsWithoutVM(ctx context.Context) ([]*Deployment, error)
	// Get VMs marked for deletion
	GetDeletingVMs(ctx context.Context) ([]*Vm, error)
	// Returns domains that need SSL certificates (verified but not yet active)
	GetDomainsNeedingCertificates(ctx context.Context) ([]*GetDomainsNeedingCertificatesRow, error)
	// Get failed deployments that need cleanup
	GetFailedDeployments(ctx context.Context) ([]*Deployment, error)
	// Get GitHub installation details
	GetGithubInstallationByID(ctx context.Context, id pgtype.UUID) (*GithubInstallation, error)
	// Get image details by ID
	GetImageByID(ctx context.Context, id pgtype.UUID) (*Image, error)
	// Get inactive deployments that need cleanup
	GetInactiveDeployments(ctx context.Context) ([]*Deployment, error)
	// Get the next available region number
	GetNextRegionNumber(ctx context.Context) (int32, error)
	// Get the next available VM number
	GetNextVMNumber(ctx context.Context) (int32, error)
	// BUILDER QUERIES
	// Get next pending build with row-level locking
	GetPendingBuild(ctx context.Context) (*Build, error)
	// Get VMs that are in pool or being initialized (for pool size calculation)
	GetPoolAndInitializingVMs(ctx context.Context) ([]*Vm, error)
	// VM QUERIES
	// Get VMs that are available in the pool
	GetPoolVMs(ctx context.Context) ([]*Vm, error)
	// Get project by ID
	GetProjectByID(ctx context.Context, id pgtype.UUID) (*Project, error)
	// PROJECT ENVIRONMENT QUERIES
	// Get project environment by ID
	GetProjectEnvironmentByID(ctx context.Context, id pgtype.UUID) (*ProjectEnvironment, error)
	// DEPLOYMENT QUERIES
	// Get deployments in queued state (no build assigned)
	GetQueuedDeployments(ctx context.Context) ([]*Deployment, error)
	// Get all ready deployments grouped by project+environment
	GetReadyDeployments(ctx context.Context) ([]*Deployment, error)
	// BUILD QUERIES
	// Get builds that have been in "building" state for too long
	GetTimedOutBuilds(ctx context.Context) ([]*Build, error)
	// DOMAIN QUERIES
	// Get domains that need DNS verification (unverified and recently updated)
	GetUnverifiedDomains(ctx context.Context) ([]*Domain, error)
	// Get a VM by ID
	GetVMByID(ctx context.Context, id pgtype.UUID) (*Vm, error)
	// Get count of VMs by region and status
	GetVMsByRegion(ctx context.Context) ([]*GetVMsByRegionRow, error)
	// Lists certmagic data keys with a given prefix (non-recursive - no additional slashes)
	ListCertmagicDataNonRecursive(ctx context.Context, dollar_1 pgtype.Text) ([]string, error)
	// Lists all certmagic data keys with a given prefix (recursive)
	ListCertmagicDataRecursive(ctx context.Context, dollar_1 pgtype.Text) ([]string, error)
	// Loads a certmagic data entry by key
	LoadCertmagicData(ctx context.Context, key string) (*CertmagicDatum, error)
	// Mark build as building
	MarkBuildBuilding(ctx context.Context, id pgtype.UUID) error
	// Mark build as error
	MarkBuildError(ctx context.Context, id pgtype.UUID) error
	// Mark build as ready with image_id
	MarkBuildReady(ctx context.Context, arg *MarkBuildReadyParams) error
	// Mark a build as error due to timeout
	MarkBuildTimedOut(ctx context.Context, id pgtype.UUID) error
	// Mark deployment as failed
	MarkDeploymentFailed(ctx context.Context, id pgtype.UUID) error
	// Mark deployment as inactive
	MarkDeploymentInactive(ctx context.Context, id pgtype.UUID) error
	// Mark a domain as verified
	MarkDomainVerified(ctx context.Context, id pgtype.UUID) error
	// Mark VM as deleted
	MarkVMDeleted(ctx context.Context, id pgtype.UUID) error
	// Mark a VM for deletion
	MarkVMDeleting(ctx context.Context, id pgtype.UUID) error
	// Mark VM as running after container deployment
	MarkVMRunning(ctx context.Context, id pgtype.UUID) error
	// Releases a lock for a key
	ReleaseCertmagicLock(ctx context.Context, key string) (int64, error)
	// Return a VM to the pool
	ReturnVMToPool(ctx context.Context, id pgtype.UUID) error
	// Returns metadata about a certmagic data entry
	StatCertmagicData(ctx context.Context, key string) (*CertmagicDatum, error)
	// Certmagic Storage Queries
	// Stores or updates a certmagic data entry
	StoreCertmagicData(ctx context.Context, arg *StoreCertmagicDataParams) error
	// Assign VM to build
	UpdateBuildVM(ctx context.Context, arg *UpdateBuildVMParams) error
	// Update deployment with build_id and change status to building
	UpdateDeploymentWithBuild(ctx context.Context, arg *UpdateDeploymentWithBuildParams) error
	// Update deployment with image_id
	UpdateDeploymentWithImage(ctx context.Context, arg *UpdateDeploymentWithImageParams) error
	// Update deployment with vm_id and change status to ready
	UpdateDeploymentWithVM(ctx context.Context, arg *UpdateDeploymentWithVMParams) error
	// Updates the SSL certificate status for a domain
	UpdateDomainCertificateStatus(ctx context.Context, arg *UpdateDomainCertificateStatusParams) error
	// Update VM with Hetzner server ID after server creation
	UpdateVMHetznerID(ctx context.Context, arg *UpdateVMHetznerIDParams) error
	// Update VM with server details after Hetzner server creation
	UpdateVMServerDetails(ctx context.Context, arg *UpdateVMServerDetailsParams) error
}

var _ Querier = (*Queries)(nil)
