# API Service Deployment Configuration
# Background worker for deployment reconciliation
service: zeitwork-api

# API container image
image: zeitwork/api

# Deploy to same server as builder (EU-West)
servers:
  web:
    hosts:
      - 67.213.127.213 # [eu-west-1] - Primary builder node
    proxy: false

# Registry configuration
registry:
  server: ghcr.io
  username: tomhaerter
  password:
    - KAMAL_REGISTRY_PASSWORD

# Builder configuration
builder:
  arch: amd64
  context: .
  dockerfile: docker/api/Dockerfile

# Environment variables
env:
  secret:
    - NUXT_DSN

# SSH configuration
ssh:
  user: ubuntu
#
# # Health check (process-based)
# healthcheck:
#   cmd: "ps aux | grep -v grep | grep api"
#   interval: 30s
#   max_attempts: 5
