// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organisation struct {
	ID             int32
	InstallationID pgtype.Int8
	Slug           string
}

type User struct {
	ID       int32
	Username string
	GithubID int64
}

type UserInOrganisation struct {
	UserID         int32
	OrganisationID int32
}
