// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/zeitwork/zeitwork/internal/services/db"
)

type CreateProjectInput struct {
	Name        string `json:"name"`
	GithubOwner string `json:"githubOwner"`
	GithubRepo  string `json:"githubRepo"`
}

type CreateProjectPayload struct {
	Project Project `json:"project"`
}

type Deployment struct {
	ID           string          `json:"id"`
	PreviewURL   string          `json:"previewUrl"`
	Project      Project         `json:"project"`
	Organisation db.Organisation `json:"organisation"`
}

type DeploymentConnection struct {
	Nodes []Deployment `json:"nodes"`
}

type Domain struct {
	ID           string          `json:"id"`
	Name         string          `json:"name"`
	Organisation db.Organisation `json:"organisation"`
}

type LoginWithGitHubPayload struct {
	Token string  `json:"token"`
	User  db.User `json:"user"`
}

type MePayload struct {
	User db.User `json:"user"`
}

type Mutation struct {
}

type OrganisationConnection struct {
	Nodes []db.Organisation `json:"nodes"`
}

type Project struct {
	ID           string               `json:"id"`
	Name         string               `json:"name"`
	Slug         string               `json:"slug"`
	Organisation db.Organisation      `json:"organisation"`
	Deployments  DeploymentConnection `json:"deployments"`
}

type ProjectConnection struct {
	Nodes []Project `json:"nodes"`
}

type ProjectsInput struct {
	OrganisationID string `json:"organisationId"`
}

type Query struct {
}

type SetInstallationIDPayload struct {
	Organisation db.Organisation `json:"organisation"`
}
