// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/zeitwork/zeitwork/internal/services/db"
)

type CreateProjectInput struct {
	Name           string `json:"name"`
	GithubOwner    string `json:"githubOwner"`
	GithubRepo     string `json:"githubRepo"`
	OrganisationID int    `json:"organisationId"`
	Port           int    `json:"port"`
}

type CreateProjectPayload struct {
	Project Project `json:"project"`
}

type DeploymentConnection struct {
	Nodes []Deployment `json:"nodes"`
}

type Domain struct {
	ID           string          `json:"id"`
	Name         string          `json:"name"`
	Organisation db.Organisation `json:"organisation"`
}

type MePayload struct {
	User db.User `json:"user"`
}

type Mutation struct {
}

type OrganisationConnection struct {
	Nodes []db.Organisation `json:"nodes"`
}

type ProjectConnection struct {
	Nodes []Project `json:"nodes"`
}

type ProjectsInput struct {
	OrganisationID int `json:"organisationId"`
}

type Query struct {
}

type SetInstallationIDPayload struct {
	Organisation db.Organisation `json:"organisation"`
}
